export const SUBCOUNTIES = [
  'nyali',
  'mvita',
  'likoni',
  'changamwe',
  'jomvu',
  'kisauni',
  'other'
];

export const MANAGEMENT_DEPARTMENTS = [
  'tech',
  'creatives',
  'communications',
  'hr and admin',
  'case management',
  'swahilipotfm',
  'heritage',
  'hospitality',
  'health',
  'youth engagement',
  'campus ambassadors',
  'finance and procurement',
  'internal volunteers',
  'entrepreneurship',
  'events and events management',
  'partnership',
  'executive'
];

export const COHORTS = [
  'cohort 2',
  'cohort 3',
  'cohort 4'
];

export const MENTORS = [
  'Joshua Nyongesa',
  'Suad Abdulnassir Said',
  'Catherine Mwololo',
  'Caroline Kageha Saziru',
  'Joshua Sagawa',
  'Cynthia Imali Ambehi',
  'Irene Kadenyi',
  'Mark Ombacho',
  'Hassan Mohammed',
  'Iris Natasha Ayuma',
  'Vivian Edwick Ochieng',
  'Brian Bii kipkoech',
  'Gabriel Mwanzia',
  'Seth Mutie',
  'Maryam Juma',
  'Sally Ageyo Chavanji',
  'Kibibi Riziki',
  'Fatime Suleman',
  'Lilian njeri',
  'Rukia Awor',
  'Susan otieno',
  'Swabrina Mohamed Mapenzi',
  'Abdalla shuaib',
  'Alphonse Odhiambo',
  'Omar Mctito Ndegwa',
  'Mwanaharusi Juma',
  'Abubakar Mohamed',
  'Fatuma Mohamed',
  'Dorcas Mutemi',
  'Rahma Nuhu',
  'Kulthum Mohamed',
  'Wilfred Gambo',
  'Khalid Ali',
  'Rahma Nelima Salim',
  'Chiro Tunje',
  'Collins Shake',
  'Amida Said',
  'Teddy Nyenze Ndei',
  'Happy mak-osewe',
  'Humphrey Ndurya Chirudi',
  'Athman Rissasi Said',
  'Wycliff Okatch Nyaundo',
  'Salma Salim Hamid',
  'Aisha Juma M\'zani',
  'Frank Dendla',
  'Laki Ali Mwabugu',
  'Maryam Faisal',
  'Tanim Suleiman',
  'Sarah Achola',
  'Linah Mulongo',
  'Juma Ali Mwakaadzango',
  'Aisha Athman Juma',
  'Ramadhan Tanariva',
  'William Swaleh',
  'Bakari Kudoka',
  'Mary Mulunga Mwachiti',
  'Omari Bakari Beya',
  'Hafsa Meali Mwakanyenze',
  'Omar Mazera Ngedzo',
  'Getrude Shiyuka',
  'Halima Hamisi Kingi',
  'Mumba Masudi Bomu',
  'Salma Ali Abdallah',
  'Erick Simon',
  'Josephine kivendi',
  'Hassan kalama',
  'Lilian juma',
  'Amos wangige',
  'Frascisca Okoth',
  'Charity Khavakaluha',
  'Faith Kambua',
  'Priscah Kimani',
  'Shamim Hadazah',
  'Maimuna Mohammed',
  'Diana Awuor',
  'Ali Abdallah Ali',
  'Vigilance Shighi Msiko',
  'Elvis Mdari Mwaivu',
  'Nuru Juma',
  'Saadia mohamed',
  'Doctor Ogallo',
  'Amina kassim',
  'Zipporah njoki',
  'Omar faissally',
  'Sharon kabibi',
  'Erick Lenjo',
  'Rozina Njeri Mtua',
  'Mwanamgeni Suleiman',
  'Pauline Akuku Okoya',
  'Zainab Maganga',
  'Steven Odami',
  'Ian Mgainga',
  'Ahlam Wahid Ahmed',
  'Collins Raria',
  'Fatma Yahya',
  'Khadija Riziki Amani',
  'Kriss Ford',
  'Firdaus Ahmed',
  'Zainab Bilal',
  'Prize Unda Riziki',
  'Umi Sadik Shee',
  'Nuru Mahmoud',
  'Owen Odhiambo',
  'Ummi Said Omar',
  'Amina Hassan',
  'Emelda Okulu',
  'Asya Ahmed',
  'Vumbi Ali',
  'Others'
];